# Generated by Django 4.2.1 on 2023-07-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="code_phone",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="code_phone",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
