# Generated by Django 4.2.1 on 2023-08-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_historicaluser_code_phone_user_code_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
